version: '3'

services:
  webapp:
    build: ./app
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet